name: 'Action Name'
description: 'Action Description'
branding:
  icon: 'arrow-up-circle'
  color: 'blue'
inputs:
  ref:
    description: "Use a specific ref for the branch which contains the config (default: the repo's default branch, e.g. 'main')"
    required: false
  dryrun:
    description: Fetch the configuration only, don't process it.
    required: false
  verbose:
    description: Output the processed configuration
    required: false
runs:
  using: 'node16'
  main: 'dist/main.js'
