name: 'SAML.to Config Sync'
description: 'This action notifies the SAML.to backend that the repository was updated and will read and cache the contents of the `saml-to.yml` configuration file within the **default branch** in the repository.'
branding:
  icon: 'arrow-up-circle'
  color: 'blue'
inputs:
  dryrun:
    description: Fetch the configuration only, don't process it.
    required: false
  verbose:
    description: Output the processed configuration
    required: false
runs:
  using: 'node16'
  main: 'dist/main.js'
